-- Replace this file with the contents of your repo's ./docker/postgres-init.sql
-- It gets loaded into a ConfigMap and mounted at /docker-entrypoint-initdb.d/init.sql
-- so Postgres runs it automatically on first startup.
