apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-env-config
data:
  CONFIG_SERVER_URL: {{ .Values.springEnv.configServerUrl | quote }}
  EUREKA_URI: {{ .Values.springEnv.eurekaUri | quote }}
  KEYCLOAK_ISSUER_URI: {{ .Values.springEnv.keycloakIssuerUri | quote }}
  KEYCLOAK_JWKS_URI: {{ .Values.springEnv.keycloakJwksUri | quote }}
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-hosts-config
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: {{ .Values.infra.mysql.port | quote }}
  POSTGRES_HOST: postgres
  POSTGRES_PORT: {{ .Values.infra.postgres.port | quote }}
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: {{ .Values.infra.rabbitmq.port | quote }}
