apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: { app: frontend }
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          image: {{ .Values.dockerhubUser }}/frontend:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: VITE_API_BASE_URL
              value: {{ .Values.frontend.apiBaseUrl | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels: { app: frontend }
spec:
  type: {{ .Values.frontend.service.type }}
  selector: { app: frontend }
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
