apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels: { app: rabbitmq }
spec:
  replicas: 1
  selector:
    matchLabels: { app: rabbitmq }
  template:
    metadata:
      labels: { app: rabbitmq }
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.infra.rabbitmq.image }}
          ports:
            - containerPort: {{ .Values.infra.rabbitmq.port }}
            - containerPort: {{ .Values.infra.rabbitmq.managementPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels: { app: rabbitmq }
spec:
  selector: { app: rabbitmq }
  ports:
    - name: amqp
      port: {{ .Values.infra.rabbitmq.port }}
      targetPort: {{ .Values.infra.rabbitmq.port }}
    - name: management
      port: {{ .Values.infra.rabbitmq.managementPort }}
      targetPort: {{ .Values.infra.rabbitmq.managementPort }}
