apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  labels: { app: mailpit }
spec:
  replicas: 1
  selector:
    matchLabels: { app: mailpit }
  template:
    metadata:
      labels: { app: mailpit }
    spec:
      containers:
        - name: mailpit
          image: {{ .Values.infra.mailpit.image }}
          ports:
            - containerPort: {{ .Values.infra.mailpit.smtpPort }}
            - containerPort: {{ .Values.infra.mailpit.webPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
  labels: { app: mailpit }
spec:
  selector: { app: mailpit }
  ports:
    - name: smtp
      port: {{ .Values.infra.mailpit.smtpPort }}
      targetPort: {{ .Values.infra.mailpit.smtpPort }}
    - name: web
      port: {{ .Values.infra.mailpit.webPort }}
      targetPort: {{ .Values.infra.mailpit.webPort }}
