apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.infra.mysql.rootPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.infra.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.infra.postgres.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.infra.keycloak.admin | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.infra.keycloak.adminPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: newsletter-secret
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.newsletter.jwtSecret | quote }}
  CONFIRM_SECRET: {{ .Values.newsletter.confirmSecret | quote }}
  UNSUBSCRIBE_SECRET: {{ .Values.newsletter.unsubscribeSecret | quote }}
